### ISSUE TITLE
[BUG] Object of class redirect could not be converted to string.

### ISSUE THREAD

**Issue by Jogai** [BoltAuth/Auth#16]
I'm using Auth v3.0.1 on top of bolt 3.3.3.

-----------

Error on using the urls described here: https://boltauth.com/routes-urls.html

Details
-------

 - Relevant Bolt Auth Version: 3.0.1
 - Relevant Bolt Version: 3.3.3
 - PHP version: PHP 7.0.22-0ubuntu0.16.04.1

Reproduction
------------

I just migrated from a simple 2.2 install to 3.3. I wasnt using boltauth but I want to. But the links wont work. The twig functions like {{ auth_auth_login() }} do work.

When visiting /auth/profile/register or /authentication/reset i got:

`ContextErrorException in Bag.php line 276:
Catchable Fatal Error: Object of class Bolt\Extension\BoltAuth\Auth\AccessControl\Redirect could not be converted to string
in Bag.php line 276
at ErrorHandler->handleError('4096', 'Object of class Bolt\Extension\BoltAuth\Auth\AccessControl\Redirect could not be converted to string', '/home/elimkerk/web/vendor/bolt/collection/src/Bag.php', '276', array('separator' => ' '))
at implode(' ', array(object(Redirect))) in Bag.php line 276
at Bag->join(' ') in RequestSanitiser.php line 49`

**Comment by amoscatelli1** [comment]
I have exactly the same issue. Can anyone help, please?

**Comment by colorando-de** [comment]
I have the same issue. My temporary (but not enough tested) solution is to add 
`public function __toString() { return $this->target; }`

in the Class Redirect in File `boltauth/auth/src/AccessControl/Redirect.php`

**Comment by Jogai** [comment]
@colorando-de thanks, but this doesnt help for me...

Does any of the 3.3.4 or higher versions fix this problem?

**Comment by xiaohutai** [comment]
Same issue for me on 3.4.2:

- Installed Bolt 3.4.2
- Installed BoltAuth/Auth extension
- Update databases
- Navigate to a non-existant page

Result:

```
ContextErrorException in Bag.php line 278:
Catchable Fatal Error: Object of class Bolt\Extension\BoltAuth\Auth\AccessControl\Redirect could not be converted to string
```

![error](https://user-images.githubusercontent.com/4630335/33443304-914e1874-d5f7-11e7-926f-7dfb2ee28ba9.png)

**Comment by SvanteRichter** [comment]
Sorry everyone for my tardiness lately...

@colorando-de Does that fix also work for you on 3.4? If so can you PR it? @xiaohutai have you tried colorando-de's fix? does it work for you?

**Comment by xiaohutai** [comment]
@SahAssar This works for me:

```
    /**
     * @return string
     */
    public function __toString() {
        return $this->target ?: '';
    }
```
It seems that `$this->target` can be `null`.

**Comment by elipeters** [comment]
@SahAssar I confirm this works also
`public function __toString() { return $this->target; }`

...though my issue was related to incorrect database password.

`extensions/vendor/boltauth/auth/src/accesscontrol/redirect.php`

**Comment by artggd** [comment]
Any update on this? I sporadically get the error too. What about merging #20?
