### ISSUE TITLE
[BUG] Install on empty Bolt 3.4 seems to crash Bolt completely? 

### ISSUE THREAD

**Issue by winehook** [BoltAuth/Auth#25]
-------

Was just trying to install this via the Extensions menu item in the Bolt toolbar on a fresh clean install of Bolt (nothing in the database).  Install failed with an error and now I'm getting this on every page (including the Bolt CMS pages themselves):

ContextErrorException in AuthServiceProvider.php line 415:
Notice: Undefined index: providers
in AuthServiceProvider.php line 415
at ErrorHandler->handleError('8', 'Undefined index: providers', '/var/www/ws/extensions/vendor/boltauth/auth/src/Provider/AuthServiceProvider.php', '415', array('app' => object(Application))) in AuthServiceProvider.php line 415
at AuthServiceProvider->registerOauthProviders(object(Application)) in AuthServiceProvider.php line 63
at AuthServiceProvider->register(object(Application)) in Application.php line 178
at Application->register(object(AuthServiceProvider)) in Manager.php line 212
at Manager->register(object(Application)) in ExtensionServiceProvider.php line 150
at ExtensionServiceProvider->boot(object(Application)) in Application.php line 197
at Application->boot() in Application.php line 91
at Application->run() in index.php line 8

Was I supposed to do something with the Providers first, before performing this install? 

Details
-------

 - Relevant Bolt Auth Version: 3.x
 - Relevant Bolt Version: 3.4.10
 - PHP version: 7.0

Reproduction
------------

I'm working on a Dockerized version of Bolt, running locally.  Fresh install with no data, no configuration, no other extensions.  

I went into the control panel and selected Extensions, then typed BoltAuth into the field.  It gave me the BoltAuth version it recommended, and I installed it.  Popped up a little window that says it was Preparing install.... and then I got an error message about something failing, I don't recall exactly what it said.  And now every page on the site gives me the message in the attached screenshot.

![image 2018-04-05 at 12 13 24 pm](https://user-images.githubusercontent.com/1001606/38378300-34253b8c-38cb-11e8-80ef-1712680ab28a.png)

Happy to help debug further, but I can't seem to get Bolt to do anything but output this error at this point.  Since I'm relatively new to Bolt, not sure what happens next or how to 'undo' this extension.

Thanks.

**Comment by winehook** [comment]
For what it's worth -- I went through the process on another clean Docker install, and a bit more information:

1) The Preparing to install...... goes on a LONG time.  Like, maybe 60 seconds or so.  There are so many ... characters that the modal window stretches out way wide.  

2) The pop-up error I get after install is basically the same message that is displayed on all subsequent pages.  Screenshot below.

![image 2018-04-05 at 12 29 03 pm](https://user-images.githubusercontent.com/1001606/38378966-472ae4fa-38cd-11e8-83fb-d2b05b7e0fed.png)

3) After install, the modal window vanishes and the dashboard looks like it's ok.  But as soon as I select anything from the menu, I get the same page as above.

Thanks again.  Let me know how else I can help or if there is more information I can provide.

**Comment by SvanteRichter** [comment]
Hmm, seems to me like you have a bad config file...

Could you check what the boltauth config looks like on that system? It should have been copied from https://github.com/BoltAuth/Auth/blob/master/config/config.yml.dist the first time it is being accessed by the extension.

EDIT: That's not to say that the extension shouldn't handle that error more gracefully though.

**Comment by winehook** [comment]
Mmm -- actually as it turns out, there was a local permissions issue.  I had to chmod 777 app/config/extensions, and now it appears to be working.  I think you can close this up.

**Comment by SvanteRichter** [comment]
Alrightio, closing this :)
