### ISSUE TITLE
[BUG] Pagination not working

### ISSUE THREAD

**Issue by melcarthus** [BoltAuth/Auth#34]
-----------

The 11th entry does not show. Page does not load pagination and only the first 10 accounts are visible.

Details
-------

 - Relevant Bolt Auth Version: [ 3.0.5 | master ]
 - Relevant Bolt Version: [ 3.5.3 ]
 - PHP version: [ 7.0 ]
 - For UX/UI issues: [ Chrome Version 67.0.3396.87 (Official Build) (64-bit) ]

Happens on /bolt/extensions/auth
Add 11 accounts, you will see that there are only 10 visible.
Change 10 to 20 for example here: [https://github.com/BoltAuth/Auth/blob/f1080cec5e805b907be9c84d2943d5d2de1ed7a8/src/Controller/Backend.php#L177-L179](url) 
and you will see the accounts are still there, just no pagination.

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
other plugins that are installed
Seo 1.10
BoltForms 4.2.3
EmailSpooler 3.1.1
Sitemap 2.5.0
google/recaptcha 1.1.3
pagerfanta/pagerfanta 1.1.0
Paragonie/random_compat 2.0.15
ramsey/uuid 3.7.3

**Comment by SvanteRichter** [comment]
It seems like the pager isn't setting the page query param correctly. I try to see if I get time to fix  or if anyone else has a PR I'd be glad to merge.

**Comment by ncareau** [comment]
@SahAssar Fix is done, can you merge ? Thank you.

**Comment by zeamedia** [comment]
Hey all. Is there any update on this issue?

**Comment by melcarthus** [comment]
Yes a year ago there was a fix. Was it never merged into production?

**Comment by zeamedia** [comment]
Yes, I've just seen the fix in the linked issue - works for me as well.
I am wondering why this fix never has been merged into production.
```twig
{% include '@bolt/components/pager.twig' with { 'pager': pager.pager, 'surround' : pager.surr } only %}
```
