### ISSUE TITLE
LDAP?

### ISSUE THREAD

**Issue by JovinJovinsson** [BoltAuth/Auth#47]
Hey Team,

No issue with the project - looking to see some guidance as to where (file) I would need to inject my own code to enable LDAP as a provider?

Cheers.

**Comment by jadwigo** [comment]
BoltAuth uses Oauth2 through the Oauth2 Client library http://oauth2-client.thephpleague.com/ - https://github.com/thephpleague/oauth2-client

So your LDAP server probably needs to also work as an Oauth2 Server. Then you can configure BoltAuth to use the LDAP server as an identity provider and for authentication.

**Comment by SvanteRichter** [comment]
Closing as this is more of a how-to that has been answered, feel free to reopen if there is something left unanswered!
